export { default as AdminPage } from './Admin.jsx'
export { default as AddClient } from './AddClient.jsx'
export { default as Clients } from './Clients.jsx'
export { default as AddShippers } from './AddShipers.jsx'
export { default as Shippers } from './Shipers.jsx'
export { default as AddConsignessComp } from './AddConsignees.jsx'
export { default as Conignees } from './Conigness.jsx'
export { default as AddDispatch} from './AddDispatch.jsx'
export { default as Dispatch} from './Dispatch.jsx'
export { default as Message} from './Message.jsx'
export { default as Chat} from './Chat.jsx'
export { default as Wallet} from './Wallet.jsx'
export { default as Rates} from './Rates.jsx'
export { default as Way} from './Way.jsx'
export { default as AdminLogin} from './AdminLogin.jsx'
export { default as AdminService} from './AddServices.jsx'